version: "3.3"
services:
  nginx:
    image: nginx
    volumes:
     - ./static/www:/usr/share/ynote/html:ro
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "${HOSTNAME}${PORT}:80"
  ynote:
    build:
      context: .
      args:
        LUA_VER: "5.4"
    depends_on:
      - nginx
    volumes:
     - .:/build
     - "${DBPATH}:/main.db"
     - "${CONF_PATH}:/ynote.lua"

