version: "3.3"
services:
  nginx:
    image: nginx
    volumes:
     - ./static/www:/usr/share/nginx/html:ro
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "${HOSTNAME}${PORT}:80"
  ynote:
    build: .
    depends_on:
      - nginx
    volumes:
     - .:/build
     - "${DBPATH}:/main.db"

